#!/bin/bash
# Display System Status

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║   URBAN AIR POLLUTION MONITORING SYSTEM - RUNNING         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✓ Backend Server"
echo "  Location: http://localhost:5001"
echo "  Mode: DEMO (Mock Data)"
echo "  Test: curl http://localhost:5001/api/health"
echo ""
echo "✓ ML Microservice"
echo "  Location: http://localhost:5000"
echo "  Mode: DEMO (Mock Forecasts)"
echo "  Test: curl http://localhost:5000/health"
echo ""
echo "✓ React Frontend"
echo "  Location: http://localhost:3000"
echo "  Status: Starting up..."
echo ""
echo "┌────────────────────────────────────────────────────────────┐"
echo "│ NEXT STEPS:                                                │"
echo "├────────────────────────────────────────────────────────────┤"
echo "│ 1. Open http://localhost:3000 in your browser             │"
echo "│ 2. Select a city: Delhi, Mumbai, or Bangalore             │"
echo "│ 3. View real-time pollution data with AQI                 │"
echo "│ 4. Click to see 7-day forecast                            │"
echo "│ 5. Check for air quality alerts                           │"
echo "└────────────────────────────────────────────────────────────┘"
echo ""
echo "Available Demo Data:"
echo "  • Delhi:     AQI 156 (Unhealthy for Sensitive Groups)"
echo "  • Mumbai:    AQI 100 (Moderate)"
echo "  • Bangalore: AQI 75 (Moderate)"
echo ""
echo "API Endpoints:"
echo "  GET  /api/health              - Backend health"
echo "  GET  /api/pollution/delhi     - Get city data"
echo "  GET  /api/forecast/delhi      - Get 7-day forecast"
echo ""
echo "📖 Documentation:"
echo "  README.md        - Project overview"
echo "  SETUP.md         - Installation guide"
echo "  RUN_INSTRUCTIONS - How to run"
echo ""
